blank_issues_enabled: false
contact_links:
  - name: Feature request
    url: https://github.com/orchetect/swift-timecode/discussions
    about: Suggest new features or improvements.
  - name: I need help setting up or troubleshooting
    url: https://github.com/orchetect/swift-timecode/discussions
    about: Questions not answered in the documentation, discussions forum, or example projects.
